{% set name = "xarray-sentinel" %}
{% set version = "0.9.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5d9d3c8fd8c9856768edfff9568d25a92a06e5840833077660af279d2def0b8a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
  run:
    - fsspec
    - python >={{ python_min }}
    - rioxarray
    - xarray >=0.18.0
    - xmlschema

test:
  imports:
    - xarray_sentinel
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bopen/xarray-sentinel
  summary: Easily explore and access the SAR data products of the Copernicus Sentinel-1 satellite mission
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TomAugspurger
    - aurghs
    - alexamici
