{% set name = "xarray-sentinel" %}
{% set version = "0.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a9f33d0d5f8cb354562b98829069757ad34d3d9a23e1387c41994b66e25f54d3

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
  run:
    - fsspec
    - python >=3.8
    - rioxarray
    - xarray >=0.18.0
    - xmlschema

test:
  imports:
    - xarray_sentinel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bopen/xarray-sentinel
  summary: Easily explore and access the SAR data products of the Copernicus Sentinel-1 satellite mission
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TomAugspurger
    - aurghs
    - alexamici
